### ISSUE TITLE
Add support to Resnet50 v1.5

### ISSUE THREAD

**Issue by moulich** [Xilinx/graffitist#1]
Hi, would like to see support for resnet50 1.5 since the mlperf is referring to this for inference benchmarks.
The model can be found in https://zenodo.org/record/2535873#.XJB4tigzZPZ

I tried to optimize the graph in the attached folder but got an error message that "Unsupported op's found in the input graph" {Mean , ArgMax} ; Exiting..

Thanks.

**Comment by sjain-stanford** [comment]
Hi @moulich, support for resnet50-v1.5 is added now, see commit - 3878099. Please test and close if it looks good.
