### ISSUE TITLE
Problems with Anaconda3

### ISSUE THREAD

**Issue by shenjunzhong** [Xilinx/graffitist#7]
It seems that the suggested Anaconda3-2019.07-linux-x86_64.sh file integretes Python 3.7.3 rather than 3.6. Please check it out. Thank you.

**Comment by sjain-stanford** [comment]
@shenjunzhong I believe it doesn't matter as long as you create a conda env with `python=3.6`.
```
conda create -n tf1.14 pip python=3.6
```
Did you see issues with the next steps?

**Comment by shenjunzhong** [comment]
It works! Thank you!
